data:
    dataset: "SHHB"
    directory : "DATA/shanghairaw/ShanghaiTech/part_B"
    # Down below fields are not used in our case
    image_size1: 768
    image_size2: 1024
    channels: 1
    channels_rgb: 3
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    # 0 for windows env
    num_workers: 0

model:
    # Down below fields are not used in our case
    type: "simple"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    batch_size: 16
    n_epochs: 4000
    n_iters: 5000000
    snapshot_freq: 20000
    validation_freq: 2000

sampling:
    batch_size: 1
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
